services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gaim
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d gaim -h localhost -p 5432"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "5432:5432" # you can remove this if the DB doesn't need host access
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: 13whisper13/studio-app:v1.0.3
    build: .
    ports:
      - "9002:9002"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
